import { create } from 'zustand';
import { 
  Material, 
  MaterialState, 
  MaterialType, 
  PurchaseRequest, 
  Approval, 
  ProcurementStatus, 
  UserRole,
  ProcurementHistoryRecord,
  ShippingInfo,
  ShippingStage,
  ShippingStageType,
} from '../types';

const initialMaterials: Material[] = [
  {
    id: 'fuel',
    type: 'fuel',
    name: '航空煤油',
    currentStock: 85000,
    dailyConsumption: 1000,
    daysRemaining: 85,
    lowStockAlert: true,
    unit: 'L',
  },
  {
    id: 'food',
    type: 'food',
    name: '食品储备',
    currentStock: 12000,
    dailyConsumption: 120,
    daysRemaining: 100,
    lowStockAlert: false,
    unit: 'kg',
  },
  {
    id: 'medicine',
    type: 'medicine',
    name: '医疗物资',
    currentStock: 500,
    dailyConsumption: 2,
    daysRemaining: 250,
    lowStockAlert: false,
    unit: '箱',
  },
];

const APPROVAL_ORDER: UserRole[] = ['leader', 'headquarters', 'superior'];

const suppliers: Record<MaterialType, string[]> = {
  fuel: ['中国极地油料公司', '国际能源运输集团', '北极油品供应'],
  food: ['南极食品供应中心', '极地后勤保障部', '科考食品加工厂'],
  medicine: ['极地医疗物资中心', '国际红十字会', '南极医药供应'],
};

const SHIPPING_STAGES: { type: ShippingStageType; name: string; location: string }[] = [
  { type: 'supplier_outbound', name: '供应商出库', location: '供应商仓库' },
  { type: 'port_assembly', name: '港口集结', location: '上海港' },
  { type: 'sea_transport', name: '海运', location: '南太平洋' },
  { type: 'antarctic_station', name: '南极补给站', location: '中山站' },
  { type: 'air_transport', name: '空运', location: '内陆空运' },
  { type: 'arrived', name: '抵站', location: '科考站仓库' },
];

export const getStageLabel = (type: ShippingStageType): string => {
  const stage = SHIPPING_STAGES.find(s => s.type === type);
  return stage?.name || type;
};

export const getStageLocation = (type: ShippingStageType): string => {
  const stage = SHIPPING_STAGES.find(s => s.type === type);
  return stage?.location || '';
};

const createShippingStages = (): ShippingStage[] => {
  return SHIPPING_STAGES.map(stage => ({
    ...stage,
    arrivedAt: null,
    completed: false,
  }));
};

export const getRoleLabel = (role: UserRole): string => {
  switch (role) {
    case 'leader': return '考察组长';
    case 'headquarters': return '总指挥';
    case 'superior': return '上级';
    default: return role;
  }
};

const getStatusLabel = (status: ProcurementStatus): string => {
  switch (status) {
    case 'pending': return '待审批';
    case 'approved': return '已批准';
    case 'procuring': return '采购中';
    case 'shipping': return '运输中';
    case 'delivered': return '已到货';
    case 'rejected': return '已拒绝';
  }
};

const createApprovals = (requestId: string): Approval[] => {
  const now = Date.now();
  return APPROVAL_ORDER.map((role, index) => ({
    id: `app-${now}-${index}`,
    requestId,
    approverRole: role,
    status: 'pending' as const,
    approvedAt: null,
    comment: '',
  }));
};

const generateShippingInfo = (materialType: MaterialType): ShippingInfo => {
  const supplierList = suppliers[materialType];
  const supplier = supplierList[Math.floor(Math.random() * supplierList.length)];
  const now = new Date();
  const expectedArrival = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  
  return {
    supplier,
    expectedArrival,
    shipmentBatch: `BATCH-${Date.now().toString(36).toUpperCase()}`,
    deliveryProgress: 0,
    currentLocation: '供应商仓库',
    stages: createShippingStages(),
    currentStage: 'supplier_outbound',
    hasRisk: false,
    riskReason: '',
    expectedDelayDays: 0,
  };
};

const createHistoryRecord = (request: PurchaseRequest, materialType: MaterialType): ProcurementHistoryRecord => {
  const approvedApproval = request.approvals.find(a => a.status === 'approved');
  return {
    id: `hist-${request.id}`,
    requestId: request.id,
    materialId: request.materialId,
    materialType,
    materialName: request.materialName,
    quantity: request.quantity,
    unit: request.unit,
    status: request.status,
    autoGenerated: request.autoGenerated,
    createdAt: request.createdAt,
    approvedAt: approvedApproval?.approvedAt || undefined,
    deliveredAt: request.deliveredAt,
    rejectionReason: request.rejectionReason,
    approvals: [...request.approvals],
    shippingInfo: request.shippingInfo ? { ...request.shippingInfo } : undefined,
  };
};

const generateInitialRequests = (): PurchaseRequest[] => {
  const now = new Date();
  
  return [
    {
      id: 'req-001',
      materialId: 'fuel',
      materialName: '航空煤油',
      quantity: 50000,
      unit: 'L',
      status: 'pending',
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
      approvals: createApprovals('req-001'),
      autoGenerated: true,
    },
    {
      id: 'req-002',
      materialId: 'food',
      materialName: '食品储备',
      quantity: 21600,
      unit: 'kg',
      status: 'delivered',
      createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
      approvals: createApprovals('req-002').map(a => ({ ...a, status: 'approved' as const, approvedAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000) })),
      autoGenerated: true,
      deliveredAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      shippingInfo: {
        supplier: '南极食品供应中心',
        expectedArrival: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
        shipmentBatch: 'BATCH-2024-FOOD-001',
        deliveryProgress: 100,
        currentLocation: '科考站仓库',
        stages: createShippingStages().map((s, i) => ({
          ...s,
          completed: true,
          arrivedAt: new Date(now.getTime() - (18 - i * 3) * 24 * 60 * 60 * 1000),
        })),
        currentStage: 'arrived',
        hasRisk: false,
        riskReason: '',
        expectedDelayDays: 0,
        stockChange: {
          beforeStock: 12000,
          afterStock: 33600,
          beforeDays: 100,
          afterDays: 280,
          changedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
        },
      },
    },
  ];
};

const generateInitialHistory = (): ProcurementHistoryRecord[] => {
  const requests = generateInitialRequests();
  return requests.map(r => createHistoryRecord(r, r.materialId as MaterialType));
};

export const canApproveRequest = (request: PurchaseRequest, role: UserRole): boolean => {
  if (request.status !== 'pending') return false;
  
  const roleIndex = APPROVAL_ORDER.indexOf(role);
  if (roleIndex === -1) return false;
  
  for (let i = 0; i < roleIndex; i++) {
    const prevApproval = request.approvals.find(a => a.approverRole === APPROVAL_ORDER[i]);
    if (!prevApproval || prevApproval.status !== 'approved') {
      return false;
    }
  }
  
  const currentApproval = request.approvals.find(a => a.approverRole === role);
  return currentApproval?.status === 'pending';
};

const getMaterialType = (materialId: string): MaterialType => {
  const material = initialMaterials.find(m => m.id === materialId);
  return material?.type || 'fuel';
};

const REJECTION_COOLDOWN = 30000;

export const useMaterialStore = create<MaterialState>((set, get) => ({
  materials: initialMaterials,
  lowStockMaterials: initialMaterials.filter(m => m.lowStockAlert),
  pendingRequests: generateInitialRequests().filter(r => r.status === 'pending'),
  purchaseRequests: generateInitialRequests(),
  procurementHistory: generateInitialHistory(),
  selectedRequest: null,
  historyFilter: 'all',
  lastRejectedAt: {},
  
  canApprove: (request, role) => canApproveRequest(request, role),
  
  updateMaterialData: () => {
    set((state) => {
      const updatedMaterials = state.materials.map((material) => {
        const consumption = material.dailyConsumption * (0.95 + Math.random() * 0.1);
        const newStock = Math.max(0, material.currentStock - consumption / 24 / 60);
        const daysRemaining = Math.floor(newStock / material.dailyConsumption);
        
        return {
          ...material,
          currentStock: Math.round(newStock * 10) / 10,
          daysRemaining,
          lowStockAlert: daysRemaining < 90,
        };
      });

      return {
        materials: updatedMaterials,
        lowStockMaterials: updatedMaterials.filter(m => m.lowStockAlert),
        pendingRequests: state.purchaseRequests.filter(r => r.status === 'pending'),
      };
    });
  },
  
  autoGenerateLowStockRequests: () => {
    const state = get();
    const { materials, purchaseRequests, lastRejectedAt } = state;
    const now = Date.now();
    
    const lowStockMaterials = materials.filter(m => m.daysRemaining < 90);
    
    lowStockMaterials.forEach((material) => {
      const hasActiveRequest = purchaseRequests.some(
        r => r.materialId === material.id && (r.status === 'pending' || r.status === 'approved' || r.status === 'procuring' || r.status === 'shipping')
      );
      
      if (hasActiveRequest) return;
      
      const lastRejected = lastRejectedAt[material.id] || 0;
      const cooldownElapsed = now - lastRejected >= REJECTION_COOLDOWN;
      
      if (!cooldownElapsed) return;
      
      const quantity = material.dailyConsumption * 180;
      const requestId = `req-${now}-${material.id}`;
      
      const newRequest: PurchaseRequest = {
        id: requestId,
        materialId: material.id,
        materialName: material.name,
        quantity: Math.round(quantity),
        unit: material.unit,
        status: 'pending',
        createdAt: new Date(),
        approvals: createApprovals(requestId),
        autoGenerated: true,
      };
      
      const historyRecord = createHistoryRecord(newRequest, material.type);
      
      set((state) => ({
        purchaseRequests: [...state.purchaseRequests, newRequest],
        pendingRequests: [...state.purchaseRequests, newRequest].filter(r => r.status === 'pending'),
        procurementHistory: [...state.procurementHistory, historyRecord],
      }));
    });
  },
  
  createPurchaseRequest: (materialId: string, quantity: number) => {
    const state = get();
    const material = state.materials.find(m => m.id === materialId);
    
    if (!material) return;
    
    const hasPendingRequest = state.purchaseRequests.some(
      r => r.materialId === materialId && (r.status === 'pending' || r.status === 'approved' || r.status === 'procuring' || r.status === 'shipping')
    );
    
    if (hasPendingRequest) return;
    
    const requestId = `req-${Date.now()}`;
    const newRequest: PurchaseRequest = {
      id: requestId,
      materialId,
      materialName: material.name,
      quantity,
      unit: material.unit,
      status: 'pending',
      createdAt: new Date(),
      approvals: createApprovals(requestId),
      autoGenerated: false,
    };
    
    const historyRecord = createHistoryRecord(newRequest, material.type);
    
    set((state) => ({
      purchaseRequests: [...state.purchaseRequests, newRequest],
      pendingRequests: [...state.purchaseRequests, newRequest].filter(r => r.status === 'pending'),
      procurementHistory: [...state.procurementHistory, historyRecord],
    }));
  },
  
  approveRequest: (requestId: string, role: UserRole, comment: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (request.status !== 'pending') return request;
        if (!canApproveRequest(request, role)) return request;
        
        const updatedApprovals = request.approvals.map((approval) => {
          if (approval.approverRole !== role) return approval;
          return {
            ...approval,
            status: 'approved' as const,
            approvedAt: new Date(),
            comment,
          };
        });
        
        const allApproved = updatedApprovals.every(a => a.status === 'approved');
        const newStatus: ProcurementStatus = allApproved ? 'approved' : 'pending';
        
        const shippingInfo = allApproved ? generateShippingInfo(getMaterialType(request.materialId)) : undefined;
        
        return {
          ...request,
          approvals: updatedApprovals,
          status: newStatus,
          shippingInfo,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        pendingRequests: updatedRequests.filter(r => r.status === 'pending'),
        procurementHistory: updatedHistory,
      };
    });
  },
  
  rejectRequest: (requestId: string, role: UserRole, comment: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (request.status !== 'pending') return request;
        if (!canApproveRequest(request, role)) return request;
        
        const updatedApprovals = request.approvals.map((approval) => {
          if (approval.approverRole !== role) return approval;
          return {
            ...approval,
            status: 'rejected' as const,
            approvedAt: new Date(),
            comment,
          };
        });
        
        return {
          ...request,
          approvals: updatedApprovals,
          status: 'rejected' as ProcurementStatus,
          rejectionReason: comment,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      const rejectedRequest = updatedRequests.find(r => r.id === requestId);
      
      return {
        purchaseRequests: updatedRequests,
        pendingRequests: updatedRequests.filter(r => r.status === 'pending'),
        procurementHistory: updatedHistory,
        lastRejectedAt: rejectedRequest 
          ? { ...state.lastRejectedAt, [rejectedRequest.materialId]: Date.now() }
          : state.lastRejectedAt,
      };
    });
  },
  
  startProcurement: (requestId: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (request.status !== 'approved') return request;
        
        return {
          ...request,
          status: 'procuring' as ProcurementStatus,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  updateShippingProgress: (requestId: string, progress: number, location: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (!request.shippingInfo) return request;
        
        const newStatus: ProcurementStatus = progress >= 100 ? 'delivered' : progress > 0 ? 'shipping' : request.status;
        
        return {
          ...request,
          status: newStatus,
          shippingInfo: {
            ...request.shippingInfo,
            deliveryProgress: Math.min(100, Math.max(0, progress)),
            currentLocation: location,
          },
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  confirmDelivery: (requestId: string) => {
    set((state) => {
      const request = state.purchaseRequests.find(r => r.id === requestId);
      if (!request) return state;
      
      const material = state.materials.find(m => m.id === request.materialId);
      const beforeStock = material?.currentStock || 0;
      const beforeDays = material?.daysRemaining || 0;
      
      const updatedMaterials = state.materials.map((mat) => {
        if (mat.id !== request.materialId) return mat;
        
        const newStock = mat.currentStock + request.quantity;
        const daysRemaining = Math.floor(newStock / mat.dailyConsumption);
        
        return {
          ...mat,
          currentStock: newStock,
          daysRemaining,
          lowStockAlert: daysRemaining < 90,
        };
      });
      
      const updatedMaterial = updatedMaterials.find(m => m.id === request.materialId);
      const afterStock = updatedMaterial?.currentStock || 0;
      const afterDays = updatedMaterial?.daysRemaining || 0;
      
      const now = new Date();
      const completedStages = request.shippingInfo?.stages.map(stage => ({
        ...stage,
        completed: true,
        arrivedAt: stage.arrivedAt || now,
      })) || createShippingStages().map(s => ({ ...s, completed: true, arrivedAt: now }));
      
      const updatedRequests = state.purchaseRequests.map((r) => {
        if (r.id !== requestId) return r;
        return {
          ...r,
          status: 'delivered' as ProcurementStatus,
          deliveredAt: now,
          shippingInfo: r.shippingInfo ? {
            ...r.shippingInfo,
            deliveryProgress: 100,
            currentLocation: '科考站仓库',
            currentStage: 'arrived' as const,
            stages: completedStages,
            stockChange: {
              beforeStock,
              afterStock,
              beforeDays,
              afterDays,
              changedAt: now,
            },
          } : undefined,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        materials: updatedMaterials,
        lowStockMaterials: updatedMaterials.filter(m => m.lowStockAlert),
        purchaseRequests: updatedRequests,
        pendingRequests: updatedRequests.filter(r => r.status === 'pending'),
        procurementHistory: updatedHistory,
      };
    });
  },
  
  updateProcurementStatus: () => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.status === 'procuring' && request.shippingInfo) {
          const progressIncrement = request.shippingInfo.hasRisk ? 1 + Math.random() * 2 : 3 + Math.random() * 4;
          const newProgress = Math.min(100, request.shippingInfo.deliveryProgress + progressIncrement);
          const stageIndex = Math.min(SHIPPING_STAGES.length - 1, Math.floor(newProgress / (100 / SHIPPING_STAGES.length)));
          const newStage = SHIPPING_STAGES[stageIndex];
          
          const newStatus: ProcurementStatus = newProgress > 0 ? 'shipping' : 'procuring';
          
          const updatedStages = request.shippingInfo.stages.map((stage, index) => {
            if (index < stageIndex && !stage.completed) {
              return { ...stage, completed: true, arrivedAt: new Date() };
            }
            if (index === stageIndex && !stage.completed) {
              return { ...stage, arrivedAt: new Date() };
            }
            return stage;
          });
          
          return {
            ...request,
            status: newStatus,
            shippingInfo: {
              ...request.shippingInfo,
              deliveryProgress: Math.round(newProgress),
              currentLocation: newStage.location,
              currentStage: newStage.type,
              stages: updatedStages,
            },
          };
        }
        if (request.status === 'shipping' && request.shippingInfo && request.shippingInfo.deliveryProgress < 100) {
          const progressIncrement = request.shippingInfo.hasRisk ? 1 + Math.random() * 1.5 : 2 + Math.random() * 3;
          const newProgress = Math.min(100, request.shippingInfo.deliveryProgress + progressIncrement);
          const stageIndex = Math.min(SHIPPING_STAGES.length - 1, Math.floor(newProgress / (100 / SHIPPING_STAGES.length)));
          const newStage = SHIPPING_STAGES[stageIndex];
          
          const updatedStages = request.shippingInfo.stages.map((stage, index) => {
            if (index < stageIndex && !stage.completed) {
              return { ...stage, completed: true, arrivedAt: new Date() };
            }
            if (index === stageIndex && !stage.arrivedAt) {
              return { ...stage, arrivedAt: new Date() };
            }
            return stage;
          });
          
          return {
            ...request,
            shippingInfo: {
              ...request.shippingInfo,
              deliveryProgress: Math.round(newProgress),
              currentLocation: newStage.location,
              currentStage: newStage.type,
              stages: updatedStages,
            },
          };
        }
        return request;
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        const updatedRequest = updatedRequests.find(r => r.id === record.requestId);
        if (!updatedRequest) return record;
        const progressChanged = updatedRequest.shippingInfo?.deliveryProgress !== record.shippingInfo?.deliveryProgress;
        const statusChanged = updatedRequest.status !== record.status;
        const riskChanged = updatedRequest.shippingInfo?.hasRisk !== record.shippingInfo?.hasRisk;
        if (!statusChanged && !progressChanged && !riskChanged) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  updateShippingRisk: (requestId: string, hasRisk: boolean, riskReason: string, delayDays: number) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId || !request.shippingInfo) return request;
        
        return {
          ...request,
          shippingInfo: {
            ...request.shippingInfo,
            hasRisk,
            riskReason,
            expectedDelayDays: delayDays,
          },
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  selectRequest: (request) => set({ selectedRequest: request }),
  
  setHistoryFilter: (filter) => set({ historyFilter: filter }),
}));

export { APPROVAL_ORDER, getStatusLabel };
