import { create } from 'zustand';
import { 
  Material, 
  MaterialState, 
  MaterialType, 
  PurchaseRequest, 
  Approval, 
  ProcurementStatus, 
  UserRole,
  ProcurementHistoryRecord,
  ShippingInfo
} from '../types';

const initialMaterials: Material[] = [
  {
    id: 'fuel',
    type: 'fuel',
    name: '航空煤油',
    currentStock: 85000,
    dailyConsumption: 1000,
    daysRemaining: 85,
    lowStockAlert: true,
    unit: 'L',
  },
  {
    id: 'food',
    type: 'food',
    name: '食品储备',
    currentStock: 12000,
    dailyConsumption: 120,
    daysRemaining: 100,
    lowStockAlert: false,
    unit: 'kg',
  },
  {
    id: 'medicine',
    type: 'medicine',
    name: '医疗物资',
    currentStock: 500,
    dailyConsumption: 2,
    daysRemaining: 250,
    lowStockAlert: false,
    unit: '箱',
  },
];

const APPROVAL_ORDER: UserRole[] = ['leader', 'headquarters', 'superior'];

const suppliers: Record<MaterialType, string[]> = {
  fuel: ['中国极地油料公司', '国际能源运输集团', '北极油品供应'],
  food: ['南极食品供应中心', '极地后勤保障部', '科考食品加工厂'],
  medicine: ['极地医疗物资中心', '国际红十字会', '南极医药供应'],
};

export const getRoleLabel = (role: UserRole): string => {
  switch (role) {
    case 'leader': return '考察组长';
    case 'headquarters': return '总指挥';
    case 'superior': return '上级';
    default: return role;
  }
};

const getStatusLabel = (status: ProcurementStatus): string => {
  switch (status) {
    case 'pending': return '待审批';
    case 'approved': return '已批准';
    case 'procuring': return '采购中';
    case 'shipping': return '运输中';
    case 'delivered': return '已到货';
    case 'rejected': return '已拒绝';
  }
};

const createApprovals = (requestId: string): Approval[] => {
  const now = Date.now();
  return APPROVAL_ORDER.map((role, index) => ({
    id: `app-${now}-${index}`,
    requestId,
    approverRole: role,
    status: 'pending' as const,
    approvedAt: null,
    comment: '',
  }));
};

const generateShippingInfo = (materialType: MaterialType): ShippingInfo => {
  const supplierList = suppliers[materialType];
  const supplier = supplierList[Math.floor(Math.random() * supplierList.length)];
  const now = new Date();
  const expectedArrival = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  
  return {
    supplier,
    expectedArrival,
    shipmentBatch: `BATCH-${Date.now().toString(36).toUpperCase()}`,
    deliveryProgress: 0,
    currentLocation: '供应商仓库',
  };
};

const createHistoryRecord = (request: PurchaseRequest, materialType: MaterialType): ProcurementHistoryRecord => {
  const approvedApproval = request.approvals.find(a => a.status === 'approved');
  return {
    id: `hist-${request.id}`,
    requestId: request.id,
    materialId: request.materialId,
    materialType,
    materialName: request.materialName,
    quantity: request.quantity,
    unit: request.unit,
    status: request.status,
    autoGenerated: request.autoGenerated,
    createdAt: request.createdAt,
    approvedAt: approvedApproval?.approvedAt || undefined,
    deliveredAt: request.deliveredAt,
    rejectionReason: request.rejectionReason,
    approvals: [...request.approvals],
    shippingInfo: request.shippingInfo ? { ...request.shippingInfo } : undefined,
  };
};

const generateInitialRequests = (): PurchaseRequest[] => {
  const now = new Date();
  
  return [
    {
      id: 'req-001',
      materialId: 'fuel',
      materialName: '航空煤油',
      quantity: 50000,
      unit: 'L',
      status: 'pending',
      createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
      approvals: createApprovals('req-001'),
      autoGenerated: true,
    },
    {
      id: 'req-002',
      materialId: 'food',
      materialName: '食品储备',
      quantity: 21600,
      unit: 'kg',
      status: 'delivered',
      createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
      approvals: createApprovals('req-002').map(a => ({ ...a, status: 'approved' as const, approvedAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000) })),
      autoGenerated: true,
      deliveredAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      shippingInfo: {
        supplier: '南极食品供应中心',
        expectedArrival: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
        shipmentBatch: 'BATCH-2024-FOOD-001',
        deliveryProgress: 100,
        currentLocation: '科考站仓库',
      },
    },
  ];
};

const generateInitialHistory = (): ProcurementHistoryRecord[] => {
  const requests = generateInitialRequests();
  return requests.map(r => createHistoryRecord(r, r.materialId as MaterialType));
};

export const canApproveRequest = (request: PurchaseRequest, role: UserRole): boolean => {
  if (request.status !== 'pending') return false;
  
  const roleIndex = APPROVAL_ORDER.indexOf(role);
  if (roleIndex === -1) return false;
  
  for (let i = 0; i < roleIndex; i++) {
    const prevApproval = request.approvals.find(a => a.approverRole === APPROVAL_ORDER[i]);
    if (!prevApproval || prevApproval.status !== 'approved') {
      return false;
    }
  }
  
  const currentApproval = request.approvals.find(a => a.approverRole === role);
  return currentApproval?.status === 'pending';
};

const getMaterialType = (materialId: string): MaterialType => {
  const material = initialMaterials.find(m => m.id === materialId);
  return material?.type || 'fuel';
};

export const useMaterialStore = create<MaterialState>((set, get) => ({
  materials: initialMaterials,
  lowStockMaterials: initialMaterials.filter(m => m.lowStockAlert),
  pendingRequests: generateInitialRequests().filter(r => r.status === 'pending'),
  purchaseRequests: generateInitialRequests(),
  procurementHistory: generateInitialHistory(),
  selectedRequest: null,
  historyFilter: 'all',
  
  canApprove: (request, role) => canApproveRequest(request, role),
  
  updateMaterialData: () => {
    set((state) => {
      const updatedMaterials = state.materials.map((material) => {
        const consumption = material.dailyConsumption * (0.95 + Math.random() * 0.1);
        const newStock = Math.max(0, material.currentStock - consumption / 24 / 60);
        const daysRemaining = Math.floor(newStock / material.dailyConsumption);
        
        return {
          ...material,
          currentStock: Math.round(newStock * 10) / 10,
          daysRemaining,
          lowStockAlert: daysRemaining < 90,
        };
      });

      return {
        materials: updatedMaterials,
        lowStockMaterials: updatedMaterials.filter(m => m.lowStockAlert),
        pendingRequests: state.purchaseRequests.filter(r => r.status === 'pending'),
      };
    });
  },
  
  autoGenerateLowStockRequests: () => {
    const state = get();
    const { materials, purchaseRequests } = state;
    
    const lowStockMaterials = materials.filter(m => m.daysRemaining < 90);
    
    lowStockMaterials.forEach((material) => {
      const hasPendingRequest = purchaseRequests.some(
        r => r.materialId === material.id && (r.status === 'pending' || r.status === 'approved' || r.status === 'procuring' || r.status === 'shipping')
      );
      
      if (!hasPendingRequest) {
        const hasRejectedRequest = purchaseRequests.some(
          r => r.materialId === material.id && r.status === 'rejected'
        );
        
        const quantity = material.dailyConsumption * 180;
        const requestId = `req-${Date.now()}-${material.id}`;
        
        const newRequest: PurchaseRequest = {
          id: requestId,
          materialId: material.id,
          materialName: material.name,
          quantity: Math.round(quantity),
          unit: material.unit,
          status: 'pending',
          createdAt: new Date(),
          approvals: createApprovals(requestId),
          autoGenerated: true,
        };
        
        const historyRecord = createHistoryRecord(newRequest, material.type);
        
        set((state) => ({
          purchaseRequests: [...state.purchaseRequests, newRequest],
          pendingRequests: [...state.purchaseRequests, newRequest].filter(r => r.status === 'pending'),
          procurementHistory: [...state.procurementHistory, historyRecord],
        }));
      }
    });
  },
  
  createPurchaseRequest: (materialId: string, quantity: number) => {
    const state = get();
    const material = state.materials.find(m => m.id === materialId);
    
    if (!material) return;
    
    const hasPendingRequest = state.purchaseRequests.some(
      r => r.materialId === materialId && (r.status === 'pending' || r.status === 'approved' || r.status === 'procuring' || r.status === 'shipping')
    );
    
    if (hasPendingRequest) return;
    
    const requestId = `req-${Date.now()}`;
    const newRequest: PurchaseRequest = {
      id: requestId,
      materialId,
      materialName: material.name,
      quantity,
      unit: material.unit,
      status: 'pending',
      createdAt: new Date(),
      approvals: createApprovals(requestId),
      autoGenerated: false,
    };
    
    const historyRecord = createHistoryRecord(newRequest, material.type);
    
    set((state) => ({
      purchaseRequests: [...state.purchaseRequests, newRequest],
      pendingRequests: [...state.purchaseRequests, newRequest].filter(r => r.status === 'pending'),
      procurementHistory: [...state.procurementHistory, historyRecord],
    }));
  },
  
  approveRequest: (requestId: string, role: UserRole, comment: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (request.status !== 'pending') return request;
        if (!canApproveRequest(request, role)) return request;
        
        const updatedApprovals = request.approvals.map((approval) => {
          if (approval.approverRole !== role) return approval;
          return {
            ...approval,
            status: 'approved' as const,
            approvedAt: new Date(),
            comment,
          };
        });
        
        const allApproved = updatedApprovals.every(a => a.status === 'approved');
        const newStatus: ProcurementStatus = allApproved ? 'approved' : 'pending';
        
        const shippingInfo = allApproved ? generateShippingInfo(getMaterialType(request.materialId)) : undefined;
        
        return {
          ...request,
          approvals: updatedApprovals,
          status: newStatus,
          shippingInfo,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        pendingRequests: updatedRequests.filter(r => r.status === 'pending'),
        procurementHistory: updatedHistory,
      };
    });
  },
  
  rejectRequest: (requestId: string, role: UserRole, comment: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (request.status !== 'pending') return request;
        if (!canApproveRequest(request, role)) return request;
        
        const updatedApprovals = request.approvals.map((approval) => {
          if (approval.approverRole !== role) return approval;
          return {
            ...approval,
            status: 'rejected' as const,
            approvedAt: new Date(),
            comment,
          };
        });
        
        return {
          ...request,
          approvals: updatedApprovals,
          status: 'rejected' as ProcurementStatus,
          rejectionReason: comment,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        pendingRequests: updatedRequests.filter(r => r.status === 'pending'),
        procurementHistory: updatedHistory,
      };
    });
  },
  
  startProcurement: (requestId: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (request.status !== 'approved') return request;
        
        return {
          ...request,
          status: 'procuring' as ProcurementStatus,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  updateShippingProgress: (requestId: string, progress: number, location: string) => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.id !== requestId) return request;
        if (!request.shippingInfo) return request;
        
        const newStatus: ProcurementStatus = progress >= 100 ? 'delivered' : progress > 0 ? 'shipping' : request.status;
        
        return {
          ...request,
          status: newStatus,
          shippingInfo: {
            ...request.shippingInfo,
            deliveryProgress: Math.min(100, Math.max(0, progress)),
            currentLocation: location,
          },
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  confirmDelivery: (requestId: string) => {
    set((state) => {
      const request = state.purchaseRequests.find(r => r.id === requestId);
      if (!request) return state;
      
      const updatedMaterials = state.materials.map((material) => {
        if (material.id !== request.materialId) return material;
        
        const newStock = material.currentStock + request.quantity;
        const daysRemaining = Math.floor(newStock / material.dailyConsumption);
        
        return {
          ...material,
          currentStock: newStock,
          daysRemaining,
          lowStockAlert: daysRemaining < 90,
        };
      });
      
      const updatedRequests = state.purchaseRequests.map((r) => {
        if (r.id !== requestId) return r;
        return {
          ...r,
          status: 'delivered' as ProcurementStatus,
          deliveredAt: new Date(),
          shippingInfo: r.shippingInfo ? {
            ...r.shippingInfo,
            deliveryProgress: 100,
            currentLocation: '科考站仓库',
          } : undefined,
        };
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        if (record.requestId !== requestId) return record;
        const updatedRequest = updatedRequests.find(r => r.id === requestId);
        if (!updatedRequest) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        materials: updatedMaterials,
        lowStockMaterials: updatedMaterials.filter(m => m.lowStockAlert),
        purchaseRequests: updatedRequests,
        pendingRequests: updatedRequests.filter(r => r.status === 'pending'),
        procurementHistory: updatedHistory,
      };
    });
  },
  
  updateProcurementStatus: () => {
    set((state) => {
      const updatedRequests = state.purchaseRequests.map((request) => {
        if (request.status === 'approved') {
          return { ...request, status: 'procuring' as ProcurementStatus };
        }
        if (request.status === 'procuring' && request.shippingInfo) {
          const newProgress = Math.min(100, request.shippingInfo.deliveryProgress + Math.random() * 5);
          const locations = ['供应商仓库', '港口', '海运中', '南极补给站', '空运中', '科考站附近'];
          const locationIndex = Math.min(locations.length - 1, Math.floor(newProgress / 20));
          
          return {
            ...request,
            status: newProgress >= 100 ? 'shipping' : 'shipping' as ProcurementStatus,
            shippingInfo: {
              ...request.shippingInfo,
              deliveryProgress: Math.round(newProgress),
              currentLocation: locations[locationIndex],
            },
          };
        }
        if (request.status === 'shipping' && request.shippingInfo) {
          const newProgress = Math.min(100, request.shippingInfo.deliveryProgress + Math.random() * 3);
          
          return {
            ...request,
            shippingInfo: {
              ...request.shippingInfo,
              deliveryProgress: Math.round(newProgress),
            },
          };
        }
        return request;
      });
      
      const updatedHistory = state.procurementHistory.map(record => {
        const updatedRequest = updatedRequests.find(r => r.id === record.requestId);
        if (!updatedRequest || updatedRequest.status === record.status) return record;
        return createHistoryRecord(updatedRequest, record.materialType);
      });
      
      return {
        purchaseRequests: updatedRequests,
        procurementHistory: updatedHistory,
      };
    });
  },
  
  selectRequest: (request) => set({ selectedRequest: request }),
  
  setHistoryFilter: (filter) => set({ historyFilter: filter }),
}));

export { APPROVAL_ORDER, getStatusLabel };
